import { z } from 'zod';
const stReservedKeywords = new Set([
    'if',
    'then',
    'else',
    'elsif',
    'end_if',
    'case',
    'of',
    'end_case',
    'for',
    'to',
    'by',
    'do',
    'end_for',
    'while',
    'end_while',
    'repeat',
    'until',
    'end_repeat',
    'exit',
    'continue',
    'bool',
    'int',
    'dint',
    'real',
    'string',
    'sint',
    'uint',
    'lint',
    'time',
    'date',
    'byte',
    'word',
    'dword',
    'array',
    'timer',
    'fbd_timer',
    'fbd_counter',
    'true',
    'false',
    'and',
    'or',
    'xor',
    'not',
    'mod',
    'var',
    'end_var',
    'var_input',
    'var_output',
    'var_in_out',
    'var_temp',
    'var_external',
    'var_global',
    'var_access',
    'constant',
    'retain',
    'non_retain',
    'function',
    'end_function',
    'function_block',
    'end_function_block',
    'program',
    'end_program',
    'action',
    'end_action',
    'step',
    'end_step',
    'initial_step',
    'transition',
    'end_transition',
    'at',
    'with',
]);
export const TagNameSchema = z
    .string()
    .min(1, 'Name is required')
    .max(40, 'Name must be 40 characters or fewer')
    .regex(/^[A-Za-z_]/, 'Name must start with a letter or underscore')
    .regex(/^[A-Za-z0-9_]+$/, 'Only letters, digits, and underscore are allowed')
    .refine((val) => !stReservedKeywords.has(val.toLowerCase()), {
    message: 'Name cannot be a reserved keyword',
});
